# created by @jcoreio/toolchain-circle

version: 2.1

orbs:
  codecov: codecov/codecov@4.1.0
jobs:
  build:
    docker:
      - image: cimg/node:24.14.1

    steps:
      - checkout
      - run:
          name: Corepack enable
          command: sudo corepack enable
      - run:
          name: Install Dependencies
          command: |-
            env "npm_config_//registry.npmjs.org/:_authToken=$NPM_TOKEN" pnpm install --frozen-lockfile
      - run:
          name: Prepublish
          command: |
            [[ $(netstat -tnlp | grep -F 'circleci-agent') ]] || pnpm run tc prepublish
      - codecov/upload
      - run:
          name: Release
          command: |
            [[ $(netstat -tnlp | grep -F 'circleci-agent') ]] || pnpm run tc release

workflows:
  build:
    jobs:
      - build:
          context:
            - npm-readonly
            - github-release
